insert into dnd_spellschool (`id`, `name`, `slug`) values (1, 'Abjuration', 'abjuration');
insert into dnd_spellschool (`id`, `name`, `slug`) values (2, 'Conjuration', 'conjuration');
insert into dnd_spellschool (`id`, `name`, `slug`) values (3, 'Divination', 'divination');
insert into dnd_spellschool (`id`, `name`, `slug`) values (4, 'Enchantment', 'enchantment');
insert into dnd_spellschool (`id`, `name`, `slug`) values (5, 'Evocation', 'evocation');
insert into dnd_spellschool (`id`, `name`, `slug`) values (6, 'Necromancy', 'necromancy');
insert into dnd_spellschool (`id`, `name`, `slug`) values (7, 'Transmutation', 'transmutation');
insert into dnd_spellschool (`id`, `name`, `slug`) values (8, 'Illusion', 'illusion');
insert into dnd_spellschool (`id`, `name`, `slug`) values (9, 'Universal', 'universal');
insert into dnd_spellschool (`id`, `name`, `slug`) values (10, 'Conjuration/Evocation', 'conjurationevocation');
insert into dnd_spellschool (`id`, `name`, `slug`) values (11, 'Transmutation/Evocation', 'transmutationevocation');
insert into dnd_spellschool (`id`, `name`, `slug`) values (12, 'Conjuration/Necromancy', 'conjurationnecromancy');
insert into dnd_spellschool (`id`, `name`, `slug`) values (13, 'Divination/Evocation', 'divinationevocation');
insert into dnd_spellschool (`id`, `name`, `slug`) values (14, 'Evocation/Transmutation', 'evocationtransmutation');
insert into dnd_spellschool (`id`, `name`, `slug`) values (15, 'Transmutation/Divination', 'transmutationdivination');
insert into dnd_spellschool (`id`, `name`, `slug`) values (16, 'Abjuration/Evocation', 'abjurationevocation');
insert into dnd_spellschool (`id`, `name`, `slug`) values (17, 'Desert Wind', 'desert-wind');
insert into dnd_spellschool (`id`, `name`, `slug`) values (18, 'Devoted Spirit', 'devoted-spirit');
insert into dnd_spellschool (`id`, `name`, `slug`) values (19, 'Diamond Mind', 'diamond-mind');
insert into dnd_spellschool (`id`, `name`, `slug`) values (20, 'Iron Heart', 'iron-heart');
insert into dnd_spellschool (`id`, `name`, `slug`) values (21, 'Setting Sun', 'setting-sun');
insert into dnd_spellschool (`id`, `name`, `slug`) values (22, 'Shadow Hand', 'shadow-hand');
insert into dnd_spellschool (`id`, `name`, `slug`) values (23, 'Stone Dragon', 'stone-dragon');
insert into dnd_spellschool (`id`, `name`, `slug`) values (24, 'Tiger Claw', 'tiger-claw');
insert into dnd_spellschool (`id`, `name`, `slug`) values (25, 'White Raven', 'white-raven');
insert into dnd_spellschool (`id`, `name`, `slug`) values (26, 'varied', 'varied');