insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (1, 'Good', 'good');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (2, 'Air', 'air');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (3, 'Mind-Affecting', 'mind-affecting');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (4, 'Language-Dependent', 'language-dependent');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (5, 'Light', 'light');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (6, 'Force', 'force');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (7, 'Sonic', 'sonic');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (8, 'Electricity', 'electricity');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (9, 'Fire', 'fire');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (10, 'Death', 'death');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (11, 'Evil', 'evil');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (12, 'Darkness', 'darkness');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (13, 'Chaos', 'chaos');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (14, 'Fear', 'fear');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (15, 'Acid', 'acid');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (16, 'Shadow', 'shadow');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (17, 'Earth', 'earth');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (18, 'Fire or Cold', 'fire-or-cold');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (19, 'Cold', 'cold');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (20, 'Water', 'water');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (21, 'Pattern', 'pattern');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (22, 'see text for lesser spirit binding', 'see-text-for-lesser-spirit-binding');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (23, 'see text', 'see-text');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (24, 'Mind Affecting and Chaotic', 'mind-affecting-and-chaotic');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (25, 'Lawful', 'lawful');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (26, 'Chaotic', 'chaotic');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (27, 'Good or Evil', 'good-or-evil');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (28, 'Investiture', 'investiture');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (29, 'Teleportation', 'teleportation');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (30, 'Creation', 'creation');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (31, 'Ice', 'ice');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (32, 'Ectomancy', 'ectomancy');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (33, 'Incarnum', 'incarnum');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (34, 'Compulsion', 'compulsion');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (35, 'see text for align weapon', 'see-text-for-align-weapon');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (36, 'Law', 'law');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (37, 'see text for lesser planar ally', 'see-text-for-lesser-planar-ally');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (38, 'see text for lesser planar binding', 'see-text-for-lesser-planar-binding');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (39, 'see text for summon monster I', 'see-text-for-summon-monster-i');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (40, 'see text for lesser energy surge', 'see-text-for-lesser-energy-surge');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (41, 'Glamer', 'glamer');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (42, 'Summoning', 'summoning');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (43, 'see text for lesser energized shield', 'see-text-lesser-energized-shield');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (44, 'see text for lesser planar exchange', 'see-text-lesser-planar-exchange');
insert into dnd_spelldescriptor (`id`, `name`, `slug`) values (45, 'Mindset', 'mindset');