insert into dnd_spellsubschool (`id`, `name`, `slug`) values (1, 'Summoning', 'summoning');
insert into dnd_spellsubschool (`id`, `name`, `slug`) values (2, 'Creation', 'creation');
insert into dnd_spellsubschool (`id`, `name`, `slug`) values (3, 'Calling', 'calling');
insert into dnd_spellsubschool (`id`, `name`, `slug`) values (4, 'Healing', 'healing');
insert into dnd_spellsubschool (`id`, `name`, `slug`) values (5, 'Compulsion', 'compulsion');
insert into dnd_spellsubschool (`id`, `name`, `slug`) values (6, 'Phantasm', 'phantasm');
insert into dnd_spellsubschool (`id`, `name`, `slug`) values (7, 'Glamer', 'glamer');
insert into dnd_spellsubschool (`id`, `name`, `slug`) values (8, 'Teleportation', 'teleportation');
insert into dnd_spellsubschool (`id`, `name`, `slug`) values (9, 'Shadow', 'shadow');
insert into dnd_spellsubschool (`id`, `name`, `slug`) values (10, 'Scrying', 'scrying');
insert into dnd_spellsubschool (`id`, `name`, `slug`) values (11, 'Charm', 'charm');
insert into dnd_spellsubschool (`id`, `name`, `slug`) values (12, 'Figment', 'figment');
insert into dnd_spellsubschool (`id`, `name`, `slug`) values (14, 'Pattern', 'pattern');
insert into dnd_spellsubschool (`id`, `name`, `slug`) values (16, 'Polymorph', 'polymorph');
insert into dnd_spellsubschool (`id`, `name`, `slug`) values (20, 'Creation or Calling', 'creation-or-calling');
insert into dnd_spellsubschool (`id`, `name`, `slug`) values (21, 'Figment and Glamer', 'figment-and-glamer');
insert into dnd_spellsubschool (`id`, `name`, `slug`) values (22, 'Boost', 'boost');
insert into dnd_spellsubschool (`id`, `name`, `slug`) values (23, 'Counter', 'counter');
insert into dnd_spellsubschool (`id`, `name`, `slug`) values (24, 'Strike', 'strike');
insert into dnd_spellsubschool (`id`, `name`, `slug`) values (25, 'Stance', 'stance');
