insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (4, '1', 'Dungeon Master''s Guide v.3.5', 'DMG', 'Weave exciting tales of heroism filled with magic and monsters. Within these pages, you''ll discover the tools and options you need to create detailed worlds and dynamic adventures for your players to experience in the Dungeons & Dragons roleplaying game.
The revised Dungeon Master''s Guide is an essential rulebook for Dungeon Masters of the D&D game. The Dungeon Master''s Guide has been reorganized to be more user friendly. It features information on running a D&D game, adjudicating play, writing adventures, nonplayer characters (including nonplayer character classes), running a campaign, characters, magic items (including intelligent and cursed items, and artifacts), and a dictionary of special abilities and conditions. Changes have been made to the item creation rules and pricing, and prestige classes new to the Dungeon Master''s Guide are included (over 10 prestige classes). The revision includes expanded advice on how to run a campaign and instructs players on how to take full advantage of the tie-in D&D miniatures line.', NULL, 'http://www.wizards.com/default.asp?x=products/dndcore/177520000', 'dungeon-masters-guide-v35', 'media/rulebook/dungeon-masters-guide-v35.jpg', '2003-07-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (5, '1', 'Monster Manual v.3.5', 'MM', 'Fearsome and formidable foes lurk within. Encounter a horde of monsters armed and ready to battle your boldest heroes or fight alongside them. The fully illustrated pages of this book are overrun with all the creatures, statistics, spells, and strategies you need to challenge the heroic characters of any Dungeons & Dragons roleplaying game.
Over 200 creeps, critters, and creatures keep players on their toes. From aboleths to zombies, the revised Monster Manual holds a diverse cast of enemies and allies essential for any Dungeons & Dragons campaign. There are hundreds of monsters ready for action, including many new creatures never seen before. The revised Monster Manual now contains an adjusted layout that makes monster statistics easier to understand and use. It has 31 new illustrations and a new index, and contains expanded information on monster classes and playing monsters as heroes, along with information on how to take full advantage of the tie-in D&D miniatures line planned for the fall of 2003 from Wizards of the Coast, Inc.', NULL, 'http://www.wizards.com/default.asp?x=products/dndcore/177550000', 'monster-manual-v35', 'media/rulebook/monster-manual-v35.jpg', '2003-07-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (6, '1', 'Player''s Handbook v.3.5', 'PH', '', '', '', 'players-handbook-v35', 'media/rulebook/players-handbook-v35.jpg', '2000-08-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (7, '3', 'Dragonmarked', 'Dra', ' Dragonmarked offers an in-depth look at the power of dragonmarks and the thirteen dragonmarked houses of the Eberron world. It also provides exciting new options for players with dragonmarked characters, including roleplaying hooks, new feats, new prestige classes, and new spells.', '2006', '', 'dragonmarked', 'media/rulebook/dragonmarked.jpg', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (8, '3', 'Faiths of Eberron', 'FE', '', NULL, '', 'faiths-of-eberron', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (9, '3', 'Magic of Eberron', 'MoE', '', NULL, '', 'magic-of-eberron', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (10, '3', 'Races of Eberron', 'RE', 'Races of Eberron expands on the information presented about the four new Eberron races (warforged, shifter, changeling and kalashtar) as well as giving more information regarding the common races and how they differ on Eberron. It also features the ubiquitous slew of feats, prestige classes, spells and magic items to immerse your character more fully in the Eberron world.', '2005', '', 'races-of-eberron', 'media/rulebook/races-of-eberron.jpg', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (11, '3', 'Sharn: City of Towers', 'Sh', '', '', '', 'sharn-city-of-towers', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (12, '3', 'Eberron Campaign Setting', 'ECS', '', '', '', 'eberron-campaign-setting', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (13, '3', 'Player''s Guide to Eberron', 'PE', '', '', '', 'players-guide-to-eberron', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (14, '3', 'Secrets of Sarlona', 'SoS', 'Secrets of Sarlona explores the continent of Sarlona for the first time. It gives players and Dungeon Masters their first real glimpse inside the empire of Riedra, home of the Inspired and the kalashtar. It also explores the mysteries of Adar, a nation isolated from the rest of the world, and never-before seen locations. Secrets of Sarlona also presents new options (feats, prestige classes, spells, and magic items) available to Sarlonan characters and characters with psionics. ', '2007', '', 'secrets-of-sarlona', 'media/rulebook/secrets-of-sarlona.jpg', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (15, '3', 'Secrets of Xen''drik', 'SX', '', NULL, '', 'secrets-of-xendrik', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (16, '4', 'City of Splendors: Waterdeep', 'CSW', '*City of Splendors: Waterdeep* offers an in-depth examination of the great city of Waterdeep in the Forgotten Realms setting. An overview of the city includes history, a whos who, information on laws, and rules for running and playing in a Waterd havian campaign. Information on the people of Waterdeep covers non-player characters, arcane schools, armed forces, guilds, nobility, prestige classes specific to the city, and more. Also included in the book are discussions of specific Waterdeep locales, adventure locales, and new monsters. An extensive appendix gives information on new equipment, magic items,  psionic powers, poisons, spells, and more.', '2005', '', 'city-of-splendors-waterdeep', '', '2005-07-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (17, '7', 'Enemies and Allies', 'EA', '', '', '', 'enemies-and-allies', '', '2001-10-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (18, '6', 'Faiths & Pantheons', 'FP', '', NULL, '', 'faiths-pantheons', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (19, '6', 'Forgotten Realms Campaign Setting', 'FRCS', '', NULL, '', 'forgotten-realms-campaign-setting', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (20, '6', 'Magic of Faerun', 'Mag', '', NULL, '', 'magic-of-faerun', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (21, '6', 'Monster Compendium: Monsters of Faer�n', 'Mon', '', NULL, '', 'monster-compendium-monsters-of-faerun', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (22, '4', 'Player''s Guide to Faer�n', 'PG', '', '', '', 'players-guide-to-faerun', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (23, '6', 'Races of Faerun', 'Rac', '', NULL, '', 'races-of-faerun', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (24, '4', 'Serpent Kingdoms', 'SK', 'Chilling fireside tales describe the fell plans and foul actions of the horrors known as the Scaled Ones: lizardfolk, nagas, yuan-ti, and their sinister creator race, the sarrukh. Infinitely patient and ruthless, the insidious serpentfolk seek to enslave all of Faer�n''s other races to breed them like cattle. For those bold enough to peer within, Serpent Kingdoms offers an unsettlingly detailed look at the malevolent serpentfolk and lizard races of the Forgotten Realms game setting.', '2004', '', 'serpent-kingdoms', 'media/rulebook/serpent-kingdoms.jpg', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (25, '4', 'Shining South', 'ShS', '', '', '', 'shining-south', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (26, '4', 'Dragons of Faerun', 'DrF', '', NULL, '', 'dragons-of-faerun', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (27, '4', 'Champions of Ruin', 'CR', '', NULL, '', 'champions-of-ruin', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (28, '4', 'Champions of Valor', 'CV', '', NULL, '', 'champions-of-valor', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (30, '4', 'Lost Empires of Faerun', 'LE', '', NULL, '', 'lost-empires-of-faerun', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (31, '4', 'Power of Faerun', 'PF', '', NULL, '', 'power-of-faerun', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (33, '6', 'Unapproachable East', 'Una', 'Tales from beyond the Easting Reach are told with awed voices and hushed tones. Known to most of Faerun as the homeland of the Simbul, the hathrans, and the Red Wizards, the Unapproachable East is filled with dark secrets, insidious plots, and untold adventure. Discover the people, politics, cities, and societies of the region, along with the monsters, nefarious organizations, and other perils that await unwary travelers in this treacherous corner of the Forgotten Realms game setting.', '2003', '', 'unapproachable-east', '', '2003-05-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (34, '4', 'Underdark', 'Und', '', NULL, '', 'underdark', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (35, '7', 'Arms and Equipment Guide', 'AE', '', '', '', 'arms-and-equipment-guide', 'media/rulebook/arms-and-equipment-guide.jpg', '2003-03-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (36, '7', 'Book of Challenges: Dungeon Rooms, Puzzles, and Traps', 'BC', 'Danger Around Every Corner and Behind Every Screen!
The greatest threat to any adventuring party is a devious Dungeon Master. This book is spring-loaded with ideas, both subtle and sinister, that will ensure every gaming session is appropriately hazardous, including:
* Over fifty encounters designed to be dropped into any campaign.
* Scalable scenarios that can be pitted against characters from 1st to 20th level.
* Advice for creating your own deceptive and deadly situations.
Dungeon Masters who want to keep their players on their toes will be inspired by the invaluable material within these pages.
To use this accessory, a Dungeon Master also needs the Player''s Handbook, the Dungeon Master''s Guide, and the Monster Manual.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/881680000', 'book-of-challenges-dungeon-rooms-puzzles-and-traps', 'media/rulebook/book-of-challenges-dungeon-rooms-puzzles-and-traps.jpg', '2002-06-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (37, '7', 'Book of Vile Darkness', 'BV', ''Only the most indomitable minds dare to look upon the malevolent thoughts and forbidden secrets bound herein. This corrupt tome is filled with deplorable wisdom, malignant ideas, and descriptions of creatures, rites, and practices most foul. Evil permeates every word and image inscribed within it.'
-- Orcus, Demon Prince of the Undead
This sourcebook for the Dungeons & Dragons game is intended for mature audiences and provides a Dungeon Master with unflinching access to subject matter that will broaden any campaign. Included in a detailed look at the nature of evil and the complex challenge of confronting the many dilemmas found within its deepest shadows. Along with wicked spells, wondrous items, and artifacts, Book of Vile Darkness also provides descriptions and statistics for a host of abominable monsters, archdevils, and demon princes to pit againt the noblest of heroes.
To use this supplement, a Dungeon Master also needs the Player''s Handbook, the Dungeon Master''s Guide, and the Monster Manual.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/881610000', 'book-of-vile-darkness', 'media/rulebook/book-of-vile-darkness.jpg', '2002-10-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (38, '7', 'Defenders of the Faith: A Guidebook to Clerics and Paladins', 'DF', 'Divine dedication powers these crusaders.
This book spotlights the champions of deities in the D&D game, clerics and paladins. It''s packed with ways to customize cleric and paladin characters, including: 
* New feats, prestige classes, weapons, and equipment
* More uses for turning checks, and new magic items and spells designed specially for clerics and paladins
* Information about special organizations such as the Laughing Knives and the Stargazers
* Detailed maps of temples that players and Dungeon Masters can use as bases of operation or as enemy structures that must be brought down


Indispensable to both players and Dungeon Masters, this book adds excitement to any campaign.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/882340000', 'defenders-of-the-faith-a-guidebook-to-clerics-and-paladins', 'media/rulebook/defenders-of-the-faith-a-guidebook-to-clerics-and-paladins.jpg', '2001-05-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (39, '7', 'Deities and Demigods', 'DD', 'Source of All Divine Power
The names of Pelor, Loki, Athena, Osiris, and their kind are invoked by the devout as well as the desperate. With abilities that reach nearly beyond the scope of mortal imagination, the splendor of the gods humbles even the greatest of heroes.
This supplement for the D&D game provides everything you need to create and call upon the most powerful beings in your campaign. Included are descriptions and statistics for over seventy gods from four fully detailed pantheons. Along with suggestions for creating your own gods, Deities and Demigods also includes information on advancing characters to godhood.
To use this supplement, a Dungeon Master also needs the Player''s Handbook, the Dungeon Master''s Guide, and the Monster Manual. A player needs only the Player''s Handbook.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/881650000', 'deities-and-demigods', 'media/rulebook/deities-and-demigods.jpg', '2002-02-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (40, '5', 'Dungeon Master''s Guide II', 'DMG2', '', '', '', 'dungeon-masters-guide-ii', '', '2005-06-23');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (41, '7', 'Epic Level Handbook', 'EL', 'Legends Begin Here
Songs are sung and tales are told of heroes who have advanced beyond most adventuring careers. They confront mightier enemies and face deadlier challenges, using powers and abilities that rival even the gods.
This supplement for the D&D game provides everything you need to transcend the first twenty levels of experience and advance characters to virtually unlimited levels of play. Along with epic magic items, epic monsters, and advice on running an epic campaign, the Epic Level Handbook also features epic NPCs from the Forgotten Realms and Greyhawk campaign settings.
To use this supplement, a Dungeon Master also needs the Player''s Handbook, the Dungeon Master''s Guide, and the Monster Manual. A player needs only the Player''s Handbook.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/881690000', 'epic-level-handbook', 'media/rulebook/epic-level-handbook.jpg', '2002-07-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (42, '7', 'Fiend Folio', 'FF', '', '', '', 'fiend-folio', 'media/rulebook/fiend-folio.jpg', '2003-04-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (43, '7', 'Manual of the Planes', 'MP', 'Visit New Dimensions
The most powerful adventurers know that great rewards--and great perils--await them beyond the world they call home. From the depths of Hell to the heights of Mount Celestia, from the clockwork world of Mechanus to the swirling chaos of Limbo, these strange and terrifying dimensions provide new challenges to adventurers who travel there. Manual of the Planes is your guidebook on a tour of the multiverse.
This supplement for the D&D game provides everything you need to know before you visit other planes of existence. Included are new prestige classes, spells, monsters, and magic items. Along with descriptions of dozens of new dimensions, Manual of the Planes includes rules for creating your own planes.
To use this supplement, a Dungeon Master also needs the Player''s Handbook, the Dungeon Master''s Guide, and the Monster Manual. A player needs only the Player''s Handbook.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/882420000', 'manual-of-the-planes', 'media/rulebook/manual-of-the-planes.jpg', '2001-09-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (44, '7', 'Masters of the Wild: A Guidebook to Barbarians, Druids, and Rangers', 'MW', 'These Forces of Nature Can Weather Any Storm
Barbarians, druids, and rangers are the rugged and noble champions of untamed lands. This book teems with new ways to customize even the most seasoned characters, including:


* New feats, weapons, spells, and magic items.
* Improved, more detailed rules for the wild shape ability.
* New prestige classes such as the frenzied berserker, the windrider, and the oozemaster.
* A new type of magic item -- the infusion.


Dungeon Masters and players who want to add a new dimension to their barbarians, druids, and rangers will uncover a cache of indispensable material within these pages.
To use this accessory, a Dungeon Master also needs the Player''s Handbook, the Dungeon Master''s Guide, and the Monster Manual. A player needs only the Player''s Handbook.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/881640000', 'masters-of-the-wild-a-guidebook-to-barbarians-druids-and-rangers', 'media/rulebook/masters-of-the-wild-a-guidebook-to-barbarians-druids-and-rangers.jpg', '2002-02-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (45, '5', 'Monster Manual II', 'MM2', 'Even Greater Threats Await!
As heroes grow in power, they seek out more formidable adversaries. Whether sinister or seductive, ferocious or foul, the creatures lurking within these pages will challenge the most experienced characters of any campaign.
This supplement for the D&D game unleashes a horde of monsters to confront characters at all levels of play, including several with Challenge Ratings of 21 or higher. Inside are old favorites such as the death knight and the gem dragons, as well as all-new creatures such as the bronze serpent, the effigy, and the fiendwurm. Along with updated and expanded monster creation rules, Monster Manual II provides an inexhaustible source of ways to keep even the toughest heroes fighting and running for their lives.
To use this supplement, a Dungeon Master also needs the Player''s Handbook and the Dungeon Master''s Guide. A player needs only the Player''s Handbook.', '', 'http://www.wizards.com/default.asp?x=products/dndacc/882680000', 'monster-manual-ii', 'media/rulebook/monster-manual-ii.jpg', '2002-09-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (46, '7', 'Psionics Handbook 3.0', 'PsH3_', '', NULL, '', 'psionics-handbook-30', '', '2001-01-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (47, '7', 'Savage Species', 'SS', 'A New Breed of Adventurer
Whether wondrous or wicked, some monsters have a calling that reaches beyond the ordinary existence of their kind. Traveling alongside other intrepid characters, these heroic creatures carve their places in legend with sword, spell, tooth, and claw.
This supplement for the D&D game provides everything you need to play a monster as a character or to make the monsters your heroes fight even more formidable. Inside are over 50 all-new monster classes that show how creatures develop their characteristics and abilities as they gain levels. Along with new prestige classes and monster templates, Savage Species also features new feats, spells, magic items, and more.
To use this supplement, a Dungeon Master also needs the Player''s Handbook, the Dungeon Master''s Guide, and the Monster Manual. A player needs only the Player''s Handbook and the Monster Manual.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/881580000', 'savage-species', 'media/rulebook/savage-species.jpg', '2003-02-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (48, '7', 'Song and Silence: A Guidebook to Bards and Rogues', 'SaS', 'Finesse and Versatility Make Powerful Allies
Bards and rogues rely on a stunning array of skills and abilities to give them an edge over any adversary. Packed with new ways to customize even the most artful characters this book includes:

* New feats, prestige classes, weapons, spells, magic items, and equipment.
* Complete guidelines for trapmaking, including 90 sample traps.
* Descriptions of a wide range of thieves'' guilds and bardic colleges.
* Detailed rules for flanking opponents in combat.

Dungeon Masters and players who want to add a new dimension to their bards and rogues will find a wealth of indispensable material within these pages.
To use this accessory, a Dungeon Master also needs the Player''s Handbook, the Dungeon Master''s Guide, and the Monster Manual. A player needs only the Player''s Handbook.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/886680000', 'song-and-silence-a-guidebook-to-bards-and-rogues', 'media/rulebook/song-and-silence-a-guidebook-to-bards-and-rogues.jpg', '2001-12-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (49, '7', 'Stronghold Builder''s Guidebook', 'SB', 'Defenses Wrought of Mortar and Magic
Heroes need impregnable fortresses to assault, wondrous towers to explore, and majestic castles to protect. This book is stocked with everything needed to design any fortified structure imaginable, including:

* Over 150 new magic items
* More than two dozen magical augmentations for stronghold walls
* Rules for magic portals, mobile strongholds, and trap creation
* Five complete strongholds, including maps, ready for immediate use

Players and Dungeon Masters who want to create customized strongholds will find all the construction materials they need within these pages.
To use this accessory, a player or Dungeon Master also needs the Player''s Handbook.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/881660000', 'stronghold-builders-guidebook', 'media/rulebook/stronghold-builders-guidebook.jpg', '2002-01-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (50, '7', 'Sword and Fist: A Guidebook to Monks and Fighters', 'SF', '', '', '', 'sword-and-fist-a-guidebook-to-monks-and-fighters', 'media/rulebook/sword-and-fist-a-guidebook-to-monks-and-fighters.jpg', '2001-01-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (51, '7', 'Tome and Blood: A Guidebook to Wizards and Sorcerers', 'TB', 'A Spell Is Better than a Thousand Words
Every mystic library reserves a place for this single potent volume of arcane lore. It''s packed with ways to customize sorcerer and wizard characters, including:

* New feats, spells, and magic items.
* New prestige classes, including the dragon disciple, fatespinner, and pale master.
* Information about special organizations such as the Broken Wands and the Arcane Order.
* Maps of a mages'' guildhall and a home that a sorcerer and a wizard share.

Tome and Blood is indispensable to players and Dungeon Masters who want to add a new dimension to sorcerers and wizards.
To use this accessory, a Dungeon Master also needs the Player''s Handbook, the Dungeon Master''s Guide, and the Monster Manual. A player needs only the Player''s Handbook.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/882380000', 'tome-and-blood-a-guidebook-to-wizards-and-sorcerers', 'media/rulebook/tome-and-blood-a-guidebook-to-wizards-and-sorcerers.jpg', '2001-07-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (52, '5', 'Book of Exalted Deeds', 'BE', 'Strike Down Evil with the Sword of Enlightenment
Only those who are pure in word, thought, and deed may look upon the knowledge gathered within this blessed tome. For the blinding truths inscribed within offer nothing but redemption or destruction for the wicked. May these consecrated pages forever illuminate the paths of the righteous.
-- Raziel the Crusader, ruler of the Platinum Heaven
As the Book of Vile Darkness was a resource book on the most evil elements of campaign play, the Book of Exalted Deeds focuses instead on the availability of good resources and features in the D&D spectrum.
Included are new exalted feats, prestige classes, races, spells, magic items, and descriptions and statistics for a host of creatures and celestial paragons to ally with virtuous characters. The Book of Exalted Deeds also provides descriptions and statistics for a host of creatures and celestial paragons to ally with virtuous characters.
Book of Exalted Deeds is the second title in the line of Dungeons & Dragons products specifically aimed at a mature audience. 
To use this supplement, a Dungeon Master also needs the Player''s Handbook, Dungeon Master''s Guide, and Monster Manual. A player needs only the Player''s Handbook.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/880260000', 'book-of-exalted-deeds', 'media/rulebook/book-of-exalted-deeds.jpg', '2003-10-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (53, '5', 'CityScape', 'Ci', 'As Deadly as Any Dungeon
There''s more to adventuring than crawling around in dungeons. The city holds many avenues of peril and intrigue. It teems with adventure and offers unsurpassed opportunities and challenges. Dark alleys, busy guildhalls, rowdy taverns, fetid sewers, and palatial manors hold secrets to be discovered and mysteries to be explored.
This supplement for the DUNGEONS & DRAGONS game reveals the city in all its grandeur and grimness. It makes the urban dungeon feel alive with politics and power, especially through influential guilds. This tome also describes new feats, spells, urban terrain, hazards, and monsters guaranteed to make the party''s next visit to the city a vibrant and exhilarating event.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/953867200', 'cityscape', 'media/rulebook/cityscape.jpg', '2006-11-07');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (54, '5', 'Complete Adventurer', 'CAd', 'Sharpen Your Survival Skills
Taverns are filled with tales of talented heroes and their breathtaking exploits. The prowess and ingenuity of these remarkable characters gives them the edge to succeed where others cannot.
This supplement for the D&D game provides everything you need to sharpen the skills and enhance the abilities of characters of any class. Along with new base classes, prestige classes, feats, spells, monsters, and magic items, Complete Adventurer provides alternate uses for skills and other options that expand the capabilities of the most versatile heroes.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/177290000', 'complete-adventurer', 'media/rulebook/complete-adventurer.jpg', '2005-01-13');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (55, '5', 'Complete Arcane', 'CAr', 'Master Eldritch Secrets and Formidable Power
Myth and mystery surround those who wield the awe-inspiring might of arcane magic. Whether through ancient knowledge, innate talent, or supernatural gift, these formidable and versatile spellcasters command powers beyond measure.
This supplement for the D&D game provides everything you need to expand the power of arcane magic for characters of any class. Along with new base classes, prestige classes, feats, spells, monsters, and magic items, Complete Arcane provides guidelines for spell duels, arcane organizations, and other aspects of a campaign world imbued with magic.', '', 'http://www.wizards.com/default.asp?x=products/dndacc/179250000', 'complete-arcane', 'media/rulebook/complete-arcane.jpg', '2004-11-18');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (56, '5', 'Complete Divine', 'CD', 'Wield Power Granted by the Gods
Legends tell of brave champions whose unwavering faith earned them the favor of the gods. Empowered by the might and magic of their deity, these devoted characters transcend the realm of mere heroes.
This supplement for the D&D game provides everything you need to create divinely inspired characters of any class. Along with new base classes, prestige classes, feats, spells, magic items, and relics, Complete Divine also provides guidelines for incorporating religion -- from mysterious cults to powerful theocracies -- into your campaign.
Cover Illustration: Matt Cavotta. (The credits in the printed product incorrectly credited the cover art to another artist. We apologize to Matt for this error.)', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/880360000', 'complete-divine', 'media/rulebook/complete-divine.jpg', '2004-05-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (57, '5', 'Complete Champion', 'CC', 'New options for heroes with a divine cause.
Complete Champion focuses on the divine champion archetype and provides new rules options for characters who enjoy battling for a cause, defeating foes using divine power, and going on quests that mean more than simply defeating the bad guy and grabbing the treasure. This book also helps Dungeon Masters run quest-themed campaigns and adventures.
In addition to providing various archetypes for characters, Complete Champion includes new feats and prestige classes. The book features dozens of deity- and belief-themed organizations, turning religion and holy (or unholy) power into something characters of all classes can use. For the Dungeon Master, this book contains information on constructing and running quests and holy missions. It assists the DM in helping all characters in the party to pursue divine paths simultaneously.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/955647200', 'complete-champion', 'media/rulebook/complete-champion.jpg', '2007-06-05');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (58, '5', 'Complete Mage', 'CM', 'Arcane Power at Your Fingertips
Every sentient creature is born with some potential to work magic. However, true mastery of arcane magic requires skill, practice, and power beyond the reach of common folk specifically, the power to harness raw magic and shape it into a desired effect. You are among those gifted few who have learned to channel arcane magic, shaping it to serve your creative or destructive whims.
This D&D supplement is intended for players and Dungeon Masters. In addition to providing the definitive treatise on arcane magic, it expands the character options available to users of arcane magic, including bards, sorcerers, wizards, assassins, warlocks, and wu jen. Herein you''ll find never-before-seen prestige classes, spells and invocations, magic items, alchemical items, heritage feats, and reserve feats (a new type of feat that grants special abilities to those who remain charged with magical power). Alternative class features give other character classes from the barbarian to the rogue a little taste of what it''s like to be an arcanist without sacrificing their core identities.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/953847200', 'complete-mage', 'media/rulebook/complete-mage.jpg', '2006-10-10');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (59, '5', 'Complete Psionic', 'CP', '', '', '', 'complete-psionic', 'media/rulebook/complete-psionic.jpg', '2006-04-11');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (60, '5', 'Complete Scoundrel', 'CS', 'Fair Fights are for Suckers
In a world filled with monsters and villains, a little deception and boldness goes a long way. You know how to take advantage of every situation, and you don''t mind getting your hands dirty. Take the gloves off? Ha! You never put them on. You infuriate your foes and amaze your allies with your ingenuity, resourcefulness, and style. For you, every new predicament is an opportunity in disguise, and with each sweet victory your notoriety grows. That is how legends are made.
This D&D supplement gives you everything you need to get the drop on your foes and escape sticky situations. In addition to new feats, spells, items, and prestige classes, Complete Scoundrel presents new mechanics that put luck on your side and a special system of skill tricks that allow any character to play the part of a scoundrel. Tricky tactics aren''t just for rogues anymore. ', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/957277200', 'complete-scoundrel', 'media/rulebook/complete-scoundrel.jpg', '2007-01-16');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (61, '5', 'Complete Warrior', 'CW', 'Forge your name in battle!
The Complete Warrior provides you with an in-depth look at combat and provides detailed information on how to prepare a character for confrontation.
This title was not only compiled from various D&D sources, but contains new things as well, including new battle-oriented character classes, prestige classes, combat maneuvers, feats, spells, magic items, and equipment. The prestige classes included have been revised and updated based on player feedback, and there are rules for unusual combat situations. The Complete Warrior will assist all class types, including those classes not typically associated with melee combat. There are also tips on running a martially focused campaign and advice on how to make your own prestige classes and feats.
To use this accessory, a Dungeon Master also needs the Player''s Handbook, Dungeon Master''s Guide, and Monster Manual. A player needs only the Player''s Handbook.', '', 'http://www.wizards.com/default.asp?x=products/dndacc/176640000', 'complete-warrior', 'media/rulebook/complete-warrior.jpg', '2003-12-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (62, '5', 'Dragon Magic', 'DM', '', '', '', 'dragon-magic', 'media/rulebook/dragon-magic.jpg', '2006-09-12');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (63, '5', 'Dungeonscape', 'Du', 'Welcome to the Dungeon!
Since the dawn of the DUNGEONS & DRAGONS game, the dungeon has remained a place of mystery, excitement, and danger. Purple worms burrow through the earth, eager for their next meal. Savage orcs lurk within the darkness, ready to surge forth and lay waste to civilized lands. Strange cults, mutated monsters, and forgotten gods hide within the choking darkness of the dungeon''s halls. Nowhere else offers greater prospects for wealth, magic, and power. Yet the horrors that lurk beneath the world never give up their treasures without a fight....
This D&D supplement presents a refreshing new take on dungeon adventures. It shows Dungeon Masters how to inject excitement, innovation, and thrilling adventure into their dungeons. New rules for encounter traps allow DMs to build deadly snares to catch the unwary. For players, the factotum class is a cunning wanderer, a jack-of-all-trades who can cope with anything the dungeon throws at him. New equipment, feats, and prestige classes give adventurers the tools they need to survive the dark beneath the earth.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/956847200', 'dungeonscape', 'media/rulebook/dungeonscape.jpg', '2007-02-13');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (64, '5', 'Exemplars of Evil', 'EE', 'The Exemplars of Evil supplement shows Dungeon Masters how to construct memorable campaign villains and presents nine ready-to-play villains of various levels that can be easily incorporated into any D&D campaign. Each villainous entry provides complete statistics for the villain (or villains), as well as adventure seeds, campaign hooks, pregenerated minions, and a fully detailed lair.
ROBERT J. SCHWALB is a staff designer and developer for Green Ronin Publishing. His design credits for Wizards include the Player''s Handbook II, Tome of Magic, and Fiendish Codex II: Tyrants of the Nine Hells supplements. Robert lives in Tennessee with his patient wife and pride of cats.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/9780786943616', 'exemplars-of-evil', 'media/rulebook/exemplars-of-evil.jpg', '2007-09-18');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (65, '5', 'Expanded Psionics Handbook', 'XPH', 'Tap into the power of the mind.
Through sheer force of will, a psionic character can unleash awesome powers that rival any physical force or magical energy. Within these pages, you will discover the secrets of unlocking the magic of the mind -- the art of psionics.
With updated and increased content, including a newly balanced psionics power system, the Expanded Psionics Handbook easily integrates psionic characters, powers, and monsters into any Dungeons & Dragons campaign.
To use this supplement, a Dungeon Master also needs the Player''s Handbook, Dungeon Master''s Guide, and Monster Manual. A player needs only the Player''s Handbook.', '', 'http://www.wizards.com/default.asp?x=products/dndacc/966660000', 'expanded-psionics-handbook', 'media/rulebook/expanded-psionics-handbook.jpg', '2004-04-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (66, '5', 'Fiendish Codex I: Hordes of the Abyss', 'FCI', '', '', '', 'fiendish-codex-i-hordes-of-the-abyss', 'media/rulebook/fiendish-codex-i-hordes-of-the-abyss.jpg', '2006-06-13');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (67, '5', 'Fiendish Codex II: Tyrants of the Nine Hells', 'FCII', 'The evil that finds you might not be the one that you expect. Learn more about devils and their insidious ways in Fiendish Codex II, where both Dungeon Masters and players alike can find something useful to either enhance the evil of their devilish villains or fight it. For a sample of what''s in store for you in this tome, take a look at Dis, a list of new feats, the hellfire warlock prestige class, a list of new spells, and the assassin devil.', 'psvo', 'http://otvxdenfwyqf.com/', 'fiendish-codex-ii-tyrants-of-the-nine-hells', 'media/rulebook/fiendish-codex-ii-tyrants-of-the-nine-hells.jpg', '2006-12-12');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (68, '5', 'Frostburn', 'Fr', 'Survival at Sub-Zero
Marrow-chilling conditions, deadly hazards, and other dangers threaten explorers of frostfell environments. Whether traveling through polar regions and frozen mountaintops to ice-glazed dungeons and the Ice Wastes of the Abyss, a wintry grave awaits those who venture forth unprepared.
This supplement for the D&D game explores the impact of arctic conditions and extreme cold-weather environments on every aspect of game play. Along with rules for adapting to, navigating through, and surviving hazardous cold-weather conditions and terrain, Frostburn also includes new spells, feats, magic items, prestige classes, and monsters associated with icy realms.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/177580000', 'frostburn', 'media/rulebook/frostburn.jpg', '2004-09-23');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (69, '5', 'Heroes of Battle', 'HB', 'Prepare for WarGreat conflicts erupt between rival nations and threaten to sweep across entire continents. As armies clash in epic battles, the actions of a handful of bold heroes can turn the tide of war. Whether in the thick of combat or on a secret mission of dire importance, brave champions have an impact that echoes across the battlefield and resounds through the ages.
This supplement for the D&D game reveals the pivotal roles characters can play in the midst of great battles. With rules and options for creating or playing adventures on and around battlefields, Heroes of Battle plunges characters into wartime situations and challenges them with climactic battles of epic proportions.
To use this supplement, a Dungeon Master also needs the Player''s Handbook and Dungeon Master''s Guide. A player needs only the Player''s Handbook.
Heroes of Battle provides everything one needs to know to play a battle-oriented D&D campaign. You can build military characters with new feats, spells, uses for traditional spells, and prestige classes. Information is given on tools specific to the battlefield, including siege engines, weapons, magic items, steeds, and other exotic mounts. Battlefield terrain aspects are discussed with plenty of illustrative maps and new rules. Specific types of battlefield encounters are discussed in detail, and the book provides specific detail on designing battlefields.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/860900000', 'heroes-of-battle', 'media/rulebook/heroes-of-battle.jpg', '2005-05-19');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (70, '5', 'Heroes of Horror', 'HH', 'Heroes of Horror  provides everything players and Dungeon Masters need to play and run a horror-oriented campaign or integrate elements of creepiness & tension into their existing campaigns. Players can develop heroes or anti-heroes using new feats, new spells, new base classes and prestige classes, and new magic items. The book presents new mechanics for different types of horror, including rules for dread and tainted characters, as well as plenty of new horrific monsters and adventure seeds. Different types and genres of horror are discussed in detail.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/885227200', 'heroes-of-horror', 'media/rulebook/heroes-of-horror.jpg', '2005-10-20');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (71, '5', 'Libris Mortis: The Book of the Dead', 'LM', 'Nightmares from Beyond the Grave
Hushed voices tell spine-chilling tales of encounters with the walking dead and other unliving horrors. No other creatures have evoked such fear and fascination as this dreadful menagerie of malevolent spirits and mindless shells.
This supplement for the D&D game presents a comprehensive overview of the undead. You''ll uncover information for creating, customizing, and combating undead characters and monsters -- including strategies and tactics commonly employed by undead and those who hunt them. Libris Mortis: The Book of Undead also provides new rules, feats, spells, and prestige classes, along with a host of new monsters and monster templates.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/179240000', 'libris-mortis-the-book-of-the-dead', 'media/rulebook/libris-mortis-the-book-of-the-dead.jpg', '2004-10-14');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (72, '5', 'Lords of Madness', 'LoM', 'Unnatural Creatures of Unspeakable Evil
Trembling hands have recorded horrifying stories of encounters with aboleths, beholders, mind flayers, and other aberrations. The victims of these alien creatures are quickly overwhelmed by mind-numbing terror -- their only comfort is the hope for a quick death.
This supplement for the D&D game presents a comprehensive look at some of the most bizarre creatures ever to invade the world of fantasy roleplaying. Along with information about the physiology, psychology, society, and schemes of these strange beings, you''ll find spells, feats, tactics, and tools commonly employed by those who hunt them. Lords of Madness: The Book of Aberrations also provides new rules, prestige classes, monsters, sample encounters, and fully developed NPCs ready to instill fear in any hero.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/177410000', 'lords-of-madness', 'media/rulebook/lords-of-madness.jpg', '2005-04-14');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (73, '5', 'Magic Item Compendium', 'MIC', '', '', '', 'magic-item-compendium', 'media/rulebook/magic-item-compendium.jpg', '2007-03-13');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (74, '5', 'Magic of Incarnum', 'MoI', 'This supplement introduces a magical substance called incarnum into the D&D game. With this book, the players characters can meld incarnum the power of souls living, dead, and unborn into magical items and even their own bodies, granting them special attacks, defenses, and other abilities (much as magic items and spells do). Incarnum can be shaped and reshaped into new forms, giving characters tremendous versatility in the dungeon and on any battlefield.
 This book also features new classes, prestige classes, feats, and other options for characters wishing to explore the secrets of incarnum, as well as rules and advice for including incarnum in a D&D campaign.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/885797200', 'magic-of-incarnum', 'media/rulebook/magic-of-incarnum.jpg', '2005-09-22');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (75, '5', 'Miniatures Handbook', 'MH', 'Cries of battle fill the air!
The Miniatures Handbook gives you expanded rules for regular Dungeons & Dragons game play as well as guidelines for skirmishes and mass combats.
Included are new base classes, new prestige classes, 30 new feats, more than 65 new spells, new magic items, and weapon special abilities. Also, there are more than 35 new monsters, including formidable aspects of deities and archfiends.
Expand your battlefield with complete rules for skirmishes, squad-based fights, and even mass battles. There are also mechanics for random dungeons and rules for miniatures battle campaigns.
To use this supplement, a Dungeon Master also needs the Player''s Handbook, Dungeon Master''s Guide, and Monster Manual. A player needs only the Player''s Handbook.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/965820000', 'miniatures-handbook', 'media/rulebook/miniatures-handbook.jpg', '2003-10-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (76, '5', 'Monster Manual III', 'MM3', 'Encounter additional adversaries and allies
Lairing within these pages is an unstoppable wave of creatures ranging from ambush drake to zezir. A menagerie of beasts, behemoths and other ferocious beings, the monsters presented here are well prepared to battle or befriend the characters of any campaign.
This supplement for the D&D game offers a fully illustrated array of new creatures such as the boneclaw, eldritch giant, and web golem. Also included are advanced versions of some monsters as well as tactics sections to help DMs effectively run more complex creatures. Additionally, many entries contain information about where monsters are likely to appear in the Forgotten Realms and Eberron campaign settings.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/179210000', 'monster-manual-iii', 'media/rulebook/monster-manual-iii.jpg', '2004-01-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (77, '5', 'Monster Manual IV', 'MM4', 'An indispensable resource containing new monsters suitable for any Dungeons & Dragons game.
Monster Manual IV is the most recent volume in the bestselling Monster Manual line. Sure to be popular with both Dungeon Masters and players, this supplement to the D&D game provides descriptions for a vast array of new creatures. Each monster is illustrated and features a new stat block format that facilitates faster gameplay. In addition, the book includes sample encounters, pregenerated treasure hoards, and sidebars on how to incorporate the creatures in a Forgotten Realms or Eberron campaign. This product is tied to 2006''s Year of Dragons theme, which is a key marketing platform across the D&D RPG, novels, and miniatures brands.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/953767200', 'monster-manual-iv', 'media/rulebook/monster-manual-iv.jpg', '2006-07-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (78, '5', 'Monster Manual V', 'MM5', 'New monsters ideal for any Dungeons & Dragons game.
Monster Manual V is the most recent volume in the best-selling Monster Manual line. This 224-page D&D supplement presents a fully illustrated horde of new monsters, as well as ready-to-play variations of previously existing monsters. In addition, this supplement features maps of monster lairs, sample encounters, and tactics sections to help Dungeon Masters run the more complex creatures. Additionally, many entries contain information about where monsters are likely to appear in the Forgotten Realms and Eberron campaign settings.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/956817200', 'monster-manual-v', 'media/rulebook/monster-manual-v.jpg', '2007-07-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (79, '5', 'Planar Handbook', 'PlH', 'Explore Never-Ending Realms of Adventure
Only the most exceptional characters dare tread the infinite paths of the planes. From Sigil, the City of Doors, to the Blinding Tower at the heart of the Plane of Shadow, to the Elemental Plane of Fire''s storied City of Brass, countless perilous locations in the multiverse await bold heroes armed with remarkable talents and abilities, more than a little courage, and above all, knowledge.
This supplement for the D&D game provides everything you need to create and play characters prepared for the odyssey of planar travel, including new planar races, feats, equipment, spells, and magic items. The Planar Handbook also introduces the power of planar touchstones, along with details and advice for visiting dozens of planar sites.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/179200000', 'planar-handbook', 'media/rulebook/planar-handbook.jpg', '2004-07-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (80, '5', 'Player''s Handbook II', 'PH2', 'A follow-up to the Player''s Handbook designed to aid players and provide more character options.
The Player''s Handbook II builds upon existing materials in the Player''s Handbook. This is the first direct followup to the best-selling and most used D&D rulebook. It is specifically designed to expand the options available for players by both providing new material and increasing the uses for existing rules. Included are chapters on character race, background, classes, feats, spells, character creation, and character advancement. New rules include racial affiliations that make race matter as a character advances in level, new character classes and alternate class features for existing classes, new feats, tools for rapid character creation, and additional organization and teamwork benefits -- an option first introduced in Dungeon Master''s Guide II and Heroes of Battle.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/953747200', 'players-handbook-ii', 'media/rulebook/players-handbook-ii.jpg', '2006-05-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (81, '5', 'Races of Destiny', 'RD', 'Heroes Adapted to Adventure
Hailing from towns and villages in every corner of the world, resourceful and resilient adventurers emerge from among the races of destiny: humans, half-elves, half-orcs, and illumians. With an unparalleled drive to explore and experience, these diverse individuals have created names to last throughout the ages.
This supplement for the D&D game provides detailed information on the psychology, society, culture, behavior, religion, folklore, and other aspects of the races of destiny, including the illumians -- a new race presented here. In addition to new subraces and monster races playable as characters, Races of Destiny also provides new prestige classes, feats, spells, magic items, equipment, and guidelines for crafting memorable adventures within human settlements.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/177370000', 'races-of-destiny', 'media/rulebook/races-of-destiny.jpg', '2004-12-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (82, '5', 'Races of Stone', 'RS', '', '', '', 'races-of-stone', 'media/rulebook/races-of-stone.jpg', '2004-08-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (83, '5', 'Races of the Dragon', 'RDr', ' A new D&D sourcebook detailing races descended from dragons. 
 Races of the Dragon provides D&D players and Dungeon Masters with an in-depth look at races descended from or related to dragons. In addition to exploring the fan-favorite kobold race, Races of the Dragon introduces two new races, dragonborn and spellscales, and provides information on half-dragons. The dragonborn are a transitive race, an exciting new concept that allows players to transform from their initial race into a new one. This book also includes a wealth of cultural information and new prestige classes, feats, equipment, spells, and magic items. 
 Gwendolyn F.M. Kestrel works for Wizards of the Coast, Inc. as a game designer. Her previous design credits include the Races of Eberron (tm), Monster Manual (tm) III, and Underdark (tm) roleplaying games. Jennifer Clarke Wilkes is an editor for Wizards of the Coast, Inc. She works primarily on the Dungeons & Dragons Miniatures line but has edited various roleplaying game books. She co-authored Savage Species (tm) and Sandstorm (tm). 
 Kolja Raven Liquette is best known for authoring The Waking Lands web site. He has also published articles in Dragon Magazine. His previous publishing credits include Weapons of Legacy (tm). ', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/953690000', 'races-of-the-dragon', 'media/rulebook/races-of-the-dragon.jpg', '2006-01-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (84, '5', 'Races of the Wild', 'RW', 'Heroes Tempered by Nature
From within verdant forests, among nomadic caravans, or atop soaring cliffsides, courageous adventurers arise from the people known as the races of the wild: elves, halflings, and raptorans. Living in harmony with the natural world, these noble individuals embark on grand adventures that become fireside tales for generations to come.
This supplement for the D&D game provides detailed information on the psychology, society, culture, behavior, religion, folklore, and other aspects of the races of the wild, including raptorans -- a new race presented here. In addition to new humanoids and monster races playable as characters, Races of the Wild also provides new prestige classes, feats, spells, magic items, equipment, and guidelines for crafting adventures and campaigns within the communities of these tenacious folk.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/179280000', 'races-of-the-wild', 'media/rulebook/races-of-the-wild.jpg', '2005-02-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (85, '5', 'Sandstorm', 'Sa', 'Take the Heat
Sweltering temperatures, bone-scouring windstorms, and other dangers threaten explorers in waste environments. From arid deserts and volcanic regions to ash-choked dungeons and the lava-filled layers of Gehenna, unwary travelers may fall victim to the unrelenting hazards that await.
This supplement for the D&D game explores the impact of desert conditions and extreme hot-weather environments on every aspect of game play. Along with rules for adapting to, navigating through, and surviving hazardous hot-weather conditions and terrain, Sandstorm also includes new races, spells, feats, magic items, prestige classes, and monsters associated with deserts and other wastelands.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/177390000', 'sandstorm', '', '2005-03-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (86, '5', 'Spell Compendium', 'Sc_', '', '', '', 'spell-compendium', 'media/rulebook/spell-compendium.jpg', '2005-12-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (87, '5', 'Stormwrack', 'Sto', '', '', '', 'stormwrack', 'media/rulebook/stormwrack.jpg', '2005-08-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (88, '5', 'Tome of Battle: The Book of Nine Swords', 'ToB', 'New combat options for any D&D campaign.
Tome of Battle: The Book of Nine Swords introduces new rules for players who want interesting combat options for their characters. The nine martial disciplines presented within allow a character with the proper knowledge and focus to perform special combat maneuvers and nearly magical effects. Three new martial classes allow a character to develop his or her discipline even further. Also included are new feats and prestige classes that build on the disciplines, new magic items and spells, and new monsters and organizations.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/953787200', 'tome-of-battle-the-book-of-nine-swords', 'media/rulebook/tome-of-battle-the-book-of-nine-swords.jpg', '2006-08-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (89, '5', 'Tome of Magic', 'TM', 'Three new magic systems for any D&D campaign.
Tome of Magic introduces three new magic subsystems for the D&D game. Any or all of these systems can easily be inserted into a campaign. Pact magic gives characters the ability to channel lost souls, harnessing their abilities to gain supernatural powers. Shadow magic draws power from the mysterious Plane of Shadow. Truename magic gives characters that learn and properly use the true name of a creature or object immense power over it. All three systems introduce new base classes and spellcasting mechanics. Also included are new feats, prestige classes, magic items, and spells.', '', 'http://www.wizards.com/default.asp?x=products/dndacc/953650000', 'tome-of-magic', 'media/rulebook/tome-of-magic.jpg', '2006-03-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (90, '5', 'Unearthed Arcana', 'UA', 'A new guide to variant rules for the Dungeons & Dragons roleplaying game.
This all-new sourcebook provides D&D players and Dungeon Masters with a wide choice of variant rules for alternate roleplaying in a D&D campaign. Designed to expand the options available for customizing gameplay, these variant rules are modular and can be imported into any campaign in any amount desired. Examples of variant rules include playing core classes as prestige classes and alternate damage systems. Brand-new rules include a new system of metamagic feats and a new spell system.', NULL, 'http://www.wizards.com/default.asp?x=products/dndacc/881560000', 'unearthed-arcana', 'media/rulebook/unearthed-arcana.jpg', '2004-02-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (91, '5', 'Weapons of Legacy', 'WL', '', '', '', 'weapons-of-legacy', 'media/rulebook/weapons-of-legacy.jpg', '2005-07-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (92, '5', 'Draconomicon', 'Dr', '', NULL, '', 'draconomicon', '', '2003-11-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (93, '5', 'Drow of the Underdark', 'DrU', '', NULL, '', 'drow-of-the-underdark', '', '2007-05-08');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (94, '7', 'Ghostwalk', 'Gh', 'The city of Manifest rests atop ruins from ancient times and far above the entrance to the land of the dead. Here, the world of the living is shared equally with the deceased, who linger in physical form before finally passing through the Veil. Whether currently living or dead, residents and visitors are assured of an eternity of action and intrigue.

Ghostwalk contains everything needed to run a stand-alone campaign in and around the city of Manifest, or to integrate it into an existing world, including:

- Complete rules for playing ghost characters and advancing in the new Eidolon and Eidoloncer classes
- New prestige classes, such as the Bone Collector and the Ghost Slayer
- Over 70 new feats and 65 new spells, including Ghost Hand, Incorporeal Target Fighting, Death Armor, and Ectoplasmic Decay
- Three complete adventures, four highly detailed encounter sites, and fourteen new monsters and templates', '2003', '', 'ghostwalk', 'media/rulebook/ghostwalk3.JPG', '2003-06-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (95, '6', 'Lords of Darkness', 'LD', '', '', '', 'lords-of-darkness', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (96, '8', 'Oriental Adventures', 'OA', 'Asian magic, combat, mystery, and monsters, all with a D&D twist. It''s a beautiful book that takes its graphic inspiration from the texture of handmade papers and the grace of calligraphy mixed with the kickin'' edge of the new D&D style. Check out this new gallery of art drawn from the book, and if you haven''t bought it yet, what''s keeping you? All the great classes and races from the original 1st edition AD&D are back and much, much more. And there are more weird, wonderful, mysterious Asian-inspired monsters than ever before -- from all the varieties of lung dragon, to the grisly mamono (wouldn''t want to shake hands with one of those), to the classic hopping vampire (check him out in the Oriental Adventures excerpt). Get yourself warmed up with Chinese Ghost Story and Crouching Tiger, Hidden Dragon and then join the rest of your gaming group as they crack open their copies of the book and dive in for some serious Asian fantasy roleplaying.', '', '', 'oriental-adventures', 'media/rulebook/oriental_adventures_cover.png', '2001-10-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (97, '6', 'Silver Marches', 'SM', '', NULL, '', 'silver-marches', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (98, '9', 'Dragonlance Campaign Setting', 'DCS', '', NULL, '', 'dragonlance-campaign-setting', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (99, '5', 'Expedition to the Demonweb Pits', 'EDP', '', NULL, '', 'expedition-to-the-demonweb-pits', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (100, '3', 'Explorer''s Handbook', 'EH', '', NULL, '', 'explorers-handbook', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (101, '3', 'Five Nations', 'FN', '', NULL, '', 'five-nations', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (102, '5', 'Expedition to Castle Ravenloft', 'Rav', '', NULL, '', 'expedition-to-castle-ravenloft', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (103, '7', 'Return to the Temple of Elemental Evil', 'RT', '', '2001', '', 'return-to-the-temple-of-elemental-evil', '', '2001-06-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (104, '5', 'The Shattered Gates of Slaughtergarde', 'ShG', '', NULL, '', 'the-shattered-gates-of-slaughtergarde', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (105, '3', 'The Forge of War', 'FoW', '', '2007', '', 'forge-war', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (106, '10', 'Player''s Handbook 3.0', 'PHB', '', '2000', '', 'players-handbook-30', '', '2000-11-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (107, '1', 'Monster Manual', 'MM', '', '2000', '', 'monster-manual', 'media/rulebook/MM3.5.jpg', '2000-11-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (108, '1', 'Web', 'Web', 'Found on wizards.com or another source.
For example: Font of Inspiration - http://www.wizards.com/default.asp?x=dnd/frcc/20070606', '', '', 'web', '', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (109, '5', 'Dragon Compendium', 'DC', '', '', '', 'dragon-compendium', 'media/rulebook/Dragon_Compendium.png', NULL);
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (110, '5', 'Elder Evils', 'EE', 'When elder evils stir, the world groans; when they awaken, the world weeps. Buried in the deepest bowels of the Underdark, hidden in the farthest reaches of the multiverse, or lost in the gulfs between realities are terrible things that exist only to destroy or horribly remake creation. So mighty are these ancient beings that even the gods think twice about standing against them. Mortals who are aware
of their existence viciously suppress that knowledge and destroy any who would serve such things. Even if an elder evil can be forced back to whence it came, its mere presence changes the world forever. In short, it is a campaign ender.', '2007', '', 'elder-evils', '', '2007-12-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (111, '7', 'Feats', 'Feats', 'The definitive guidebook to feats, containing over a thousand. It contains both commonly used feats, and some more obscure ones', '2003', '', 'feats', 'media/rulebook/9781887953733_p0_v1_s260x420.jpg', '2003-03-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (112, '3', 'Dragons of Ebberon', 'DE', 'Dragons of Eberron delves into the mysterious Draconic Prophecy and various draconic organizations. It introduces the continent of Argonnessen, homeland of the dragons, and describes various adventure sites and other places of interest that have never before been presented. The remainder of the book explores dragons on the continents of Khorvaire, Sarlona, and Xen''drik and provides several ready-to-play dragons, complete with stat blocks, lairs, encounters, and adventure hooks. ', '2007', '', 'dragons-ebberon', 'media/rulebook/DragonsofEb.jpg', '2007-10-01');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (113, '3', 'Eyes of the Lich Queen', 'EotLQ', 'What begins as a simple expedition to explore an ancient jungle temple sends adventurers headlong into a search for the Dragon''s Eye, an artifact created ages ago by demons in order to gain power over dragons. But where exactly is this mysterious artifact, and why do the Cloudreavers and the Emerald Claw think the adventurers already have it? Only Lady Vol knows the truth. Her deadly cat-and-mouse game leads the characters from the wilderness of Q''barra to the wild coasts of the Lhazaar Principalities and the soaring peaks of Argonnessen. There, at last, they can learn the secret of the Dragon''s Eye and foil the lich queen''s plans... if they survive!
The 'Eyes of the Lich Queen' adventure for the Dungeons & Dragons game draws on the richness of the Eberron campaign setting. Designed for heroes of 5th level, the adventure sends them on a world-spanning journey as they battle cultists, pirates, long-dead spirits, and even dragons in their search for the enigmatic Dragon''s Eye.', '2007', '', 'eyes-lich-queen', '', '2007-04-17');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (114, '4', 'Shadowdale: The Scouring of the Land', 'S:TSotL', 'Elminsters tower lies in ruins, and the town of Shadowdale has been conquered by evil Sharrans and the nefarious forces of Zhentil Keep. To drive the villains out of Shadowdale, the heroes must organize and lead a desperate revolt of Dalesfolk against their conquerors, as well as thwart the sinister designs of Shars servants and the Zhent garrison.', '2007', '', 'shadowdale-scouring-land', '', '2007-07-17');
insert into dnd_rulebook (`id`, `dnd_edition_id`, `name`, `abbr`, `description`, `year`, `official_url`, `slug`, `image`, `published`) values (115, '5', 'Red Hand of Doom', 'RH', 'The Red Hand of Doom is an exciting super-adventure that pits heroes against an army bent on domination. Rampaging hobgoblins and their allies threaten to destroy the realm and all who stand before them. Characters who dare confront the horde soon discover that these particular hobgoblins worship Tiamat, the evil queen of dragons, and eventually come face-to-face with her draconic minions. The excerpts below include the introduction and adventure outline, two sample encounters, and statistics for the encounters. (Crafty DMs may find the encounters and their relevant statistics useful in other ways, too!)', '', 'http://www.wizards.com/default.asp?x=products/dndacc/953857400', 'red-hand-doom', 'media/rulebook/rhod_med.png', '2006-02-01');